version: '3.3'
services:
  talentprotocol:
    build: .
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - '.:/go/src/app'
    depends_on:
      - 'db'
  db:
    image: 'mongo:latest'
    volumes:
      - '.:/data/db'
    ports:
      - '27017:27017'